### ISSUE TITLE
London date

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/devroadshow2017#8]
I don't see the london dates for the October that is mentioned in the blog post is this still happening?

I do also see a github merge marker that should be removed, perhaps that caused it?

Thanks

**Comment by sandrapersing** [comment]
London is a private/internal BBC event, so I left it off the more public GitHub page (sorry for confusion!)

**Comment by jonathanKingston** [comment]
Ah ok :(. Lets close this off, the PR fixes the merge marker though.
